<?php

namespace LE\CoreBundle\Entity;

use SKCMS\LocaleBundle\Entity\Translation\TranslatableRepository;

/**
 * CountryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRepository extends TranslatableRepository
{
    
}
